services:
  pipeline-worker-manifest:
    build:
      context: .
      dockerfile: ./domains/worker_manifest/Dockerfile
    environment:
      S3_ENDPOINT: ${S3_ENDPOINT:?S3_ENDPOINT is required}
      S3_ACCESS_KEY: ${S3_ACCESS_KEY:?S3_ACCESS_KEY is required}
      S3_SECRET_KEY: ${S3_SECRET_KEY:?S3_SECRET_KEY is required}

networks:
  default:
    external: true
    name: rag-local
