services:
  pipeline-worker-parse-document:
    build:
      context: .
      dockerfile: ./domains/worker_parse_document/Dockerfile
    environment:
      BROKER_URL: ${BROKER_URL:?BROKER_URL is required}
      S3_ENDPOINT: ${S3_ENDPOINT:?S3_ENDPOINT is required}
      S3_ACCESS_KEY: ${S3_ACCESS_KEY:?S3_ACCESS_KEY is required}
      S3_SECRET_KEY: ${S3_SECRET_KEY:?S3_SECRET_KEY is required}
      SOURCE_TYPE: ${SOURCE_TYPE:-html}
      DEFAULT_SECURITY_CLEARANCE: ${DEFAULT_SECURITY_CLEARANCE:-internal}

networks:
  default:
    external: true
    name: ${STACK_NETWORK:?STACK_NETWORK is required}
