services:
  pipeline-worker-index-weaviate:
    build:
      context: .
      dockerfile: ./domains/worker_index_weaviate/Dockerfile
    environment:
      WEAVIATE_URL: ${WEAVIATE_URL:?WEAVIATE_URL is required}
      BROKER_URL: ${BROKER_URL:?BROKER_URL is required}
      S3_ENDPOINT: ${S3_ENDPOINT:?S3_ENDPOINT is required}
      S3_ACCESS_KEY: ${S3_ACCESS_KEY:?S3_ACCESS_KEY is required}
      S3_SECRET_KEY: ${S3_SECRET_KEY:?S3_SECRET_KEY is required}

networks:
  default:
    external: true
    name: ${STACK_NETWORK:?STACK_NETWORK is required}
